import type { Metadata } from "next";
import { getCssText } from "@/styles";
import localFont from "next/font/local";
import { globalStyles } from "@/styles/global";

const robotoBold = localFont({
  src: "./fonts/Roboto-Bold.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const robotoRegular = localFont({
  src: "./fonts/Roboto-Regular.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Guitar Shop",
  description: "Generated by create next app",
};

globalStyles();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>
      <body className={`${robotoBold} ${robotoRegular}`}>{children}</body>
    </html>
  );
}
